"""Structured source catalog for the Book Knowledge Library.

This file stores paraphrased knowledge units and chapter/topic metadata derived
from the user-supplied historical astrology books. It intentionally avoids
copying long source passages. Every unit retains source, page/chapter locator,
system, topics and confidence so downstream agents can retrieve evidence with
provenance and keep schools of astrology distinct.
"""

SOURCES = {
    "karma_ancient_egyptians": {
        "title": "Astrology of the Ancient Egyptians",
        "author": "Karma",
        "system": "WESTERN_TRADITIONAL",
        "coverage": [
            "zodiac signs", "planetary aspects", "rising sign", "Sun", "Moon",
            "planets", "ruler of horoscope", "nodes", "Part of Fortune",
            "fixed stars", "general judgment of nativity", "temperament",
            "riches", "health", "marriage", "children", "friends", "enemies",
            "journeys", "death", "progressed horoscope", "directions",
        ],
    },
    "raphael_guide": {
        "title": "The Guide to Astrology",
        "author": "Raphael",
        "system": "WESTERN_TRADITIONAL",
        "coverage": [
            "aspects", "orbs", "signs", "houses", "dignities", "ephemeris",
            "planet meanings", "judgment of nativity", "health", "mind",
            "money", "employment", "marriage", "children", "travel",
            "friends", "enemies", "directions", "solar returns", "transits",
            "eclipses",
        ],
    },
    "merton_heliocentric": {
        "title": "Heliocentric Astrology or Essentials of Astronomy and Solar Mentality",
        "author": "Yarmo Vedra / Holmes W. Merton",
        "system": "HELIOCENTRIC_HISTORICAL",
        "coverage": [
            "astronomy", "heliocentric astrology", "celestial sphere",
            "latitude", "longitude", "right ascension", "ecliptic",
            "zodiac", "planetary paths", "astrological laws",
            "sign functions", "Moon in signs", "planet in sign delineations",
        ],
    },
    "daath_medical": {
        "title": "Medical Astrology",
        "author": "Heinrich Daath",
        "system": "MEDICAL_ASTROLOGY",
        "coverage": [
            "basic elements", "anatomical sign rulership", "planetary powers",
            "biodynamic action", "tonicity", "atonicity", "disease symbolism",
            "sixth house", "eighth house", "triplicities", "quadruplicities",
            "planetary sympathy", "planetary antipathy", "planetary strength",
            "application", "examples", "historical longevity indications",
        ],
    },
    "white_guide": {
        "title": "A Guide To Astrology",
        "author": "Fredrick White",
        "system": "WESTERN_TRADITIONAL",
        "coverage": [
            "zodiac signs", "rulers", "planet motion", "houses", "aspects",
            "exaltation", "fall", "horoscope erection", "planet in sign",
            "radix judgment", "character", "employment", "location",
        ],
    },
}

ENTRIES = [
    {
        "id": "karma.aspect.exactness",
        "source": "karma_ancient_egyptians",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["aspects", "orbs", "strength"],
        "locator": "Planetary Aspects, around pp. 30-31",
        "summary": "Aspect strength increases as planets approach the exact angular relationship; applying/separating distance therefore matters to weighting.",
        "keywords": ["trine", "square", "opposition", "conjunction", "orb", "exact", "aspect"],
    },
    {
        "id": "raphael.aspect.hierarchy",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["aspects", "orbs"],
        "locator": "Nature and measurement of aspects, early chapters",
        "summary": "Aspects are differentiated by angular geometry and relative potency; interpretation should record both aspect type and closeness rather than use a binary present/absent flag.",
        "keywords": ["aspect", "orb", "conjunction", "sextile", "square", "trine", "opposition"],
    },
    {
        "id": "raphael.dignity.rulership",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["dignities", "rulership", "planetary_strength"],
        "locator": "Essential and Accidental Dignities, around pp. 26-27",
        "summary": "A planet's sign placement changes its condition; rulership and exaltation strengthen expression while contrary conditions such as fall/debilitation weaken or complicate it.",
        "keywords": ["dignity", "rulership", "exaltation", "fall", "planet strength", "condition"],
    },
    {
        "id": "white.dignity.sequence",
        "source": "white_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["dignities", "radix", "method"],
        "locator": "Lessons 3-8, opening instructional pages",
        "summary": "A sound radix judgment should learn planetary motion, houses and aspects, then exaltation/fall, planet placement and finally synthesize the horoscope.",
        "keywords": ["radix", "exaltation", "fall", "houses", "aspects", "judgment"],
    },
    {
        "id": "karma.nativity.scope",
        "source": "karma_ancient_egyptians",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["genethliacal", "natal", "houses", "life_areas"],
        "locator": "General Judgment of a Nativity, contents pp. 11-12",
        "summary": "Natal judgment is divided into temperament/intellect and concrete life domains including position, wealth, health, marriage, children, friends, enemies and journeys.",
        "keywords": ["nativity", "temperament", "wealth", "health", "marriage", "children", "friends", "journeys"],
    },
    {
        "id": "raphael.nativity.method",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["genethliacal", "natal", "life_areas"],
        "locator": "How to Judge a Nativity and subsequent topical chapters",
        "summary": "Judgment proceeds by combining planetary condition and houses with the topic under review, rather than reading a single placement in isolation.",
        "keywords": ["judge nativity", "health", "money", "employment", "marriage", "children", "travel"],
    },
    {
        "id": "white.signs.rulers.foundation",
        "source": "white_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["signs", "rulers", "method"],
        "locator": "Advice to Students / Lesson One",
        "summary": "Signs, their nature and planetary rulers are foundational knowledge that should precede detailed horoscope interpretation.",
        "keywords": ["sign", "zodiac", "ruler", "planet", "foundation"],
    },
    {
        "id": "karma.progressed_horoscope",
        "source": "karma_ancient_egyptians",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["progressions", "directions", "timing"],
        "locator": "The Progressed Horoscope / Concerning Directions",
        "summary": "Future-oriented judgment is treated as a separate timing layer built on the radix, not as a replacement for natal interpretation.",
        "keywords": ["progressed horoscope", "directions", "future", "timing"],
    },
    {
        "id": "raphael.transit.confirmation",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["transits", "directions", "timing", "confirmation"],
        "locator": "Transits and Eclipses, around pp. 121-122",
        "summary": "Simple contact of a transiting planet with a natal point should not automatically be read as an event; corroborating timing testimony of similar nature materially increases interpretive weight.",
        "keywords": ["transit", "direction", "confirmation", "event", "timing", "natal point"],
    },
    {
        "id": "raphael.transit.houses",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["transits", "houses", "timing"],
        "locator": "Transits and Eclipses, around pp. 121-122",
        "summary": "Transits through the mundane houses of the nativity are treated as meaningful timing testimony and should be read in house context.",
        "keywords": ["transit", "house", "mundane house", "timing"],
    },
    {
        "id": "raphael.solar_return.convergence",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["solar_returns", "directions", "timing", "confirmation"],
        "locator": "Solar Returns / Birthday Figures, immediately before Transits chapter",
        "summary": "Solar-return testimony becomes more important when it agrees in nature with another timing indication; conflicting testimony reduces confidence.",
        "keywords": ["solar return", "birthday figure", "direction", "confirmation", "timing"],
    },
    {
        "id": "raphael.eclipse.caution",
        "source": "raphael_guide",
        "system": "WESTERN_TRADITIONAL",
        "topics": ["eclipses", "timing", "caution"],
        "locator": "Transits and Eclipses",
        "summary": "Eclipses are treated cautiously rather than as automatic event triggers; context and supporting testimony are required.",
        "keywords": ["eclipse", "timing", "caution", "event"],
    },
    {
        "id": "daath.medical.combination",
        "source": "daath_medical",
        "system": "MEDICAL_ASTROLOGY",
        "topics": ["medical_astrology", "combination", "houses", "aspects"],
        "locator": "Zodiaco-Planetary Synopsis / application chapters",
        "summary": "Historical medical-astrology interpretation is combinatorial: planet, sign, aspect and house modify one another, so isolated correspondences are inadequate.",
        "keywords": ["medical astrology", "planet", "sign", "aspect", "house", "combination"],
    },
    {
        "id": "daath.strength.sixfold",
        "source": "daath_medical",
        "system": "MEDICAL_ASTROLOGY",
        "topics": ["planetary_strength", "medical_astrology"],
        "locator": "Gauging Planetary Strength, around p. 65 / scan p. 77",
        "summary": "Planetary strength is described through multiple dimensions: aspectual, positional, natural, motional, directional and temporal strength.",
        "keywords": ["drikbala", "sthanabala", "naisargika", "cheshta", "dikbala", "kalabala", "strength"],
    },
    {
        "id": "daath.houses.sixth_eighth",
        "source": "daath_medical",
        "system": "MEDICAL_ASTROLOGY",
        "topics": ["medical_astrology", "houses", "sixth_house", "eighth_house"],
        "locator": "Chapter VIII, Sixth and Eighth Houses",
        "summary": "The sixth and eighth houses receive special historical attention in medical-astrology judgment and must be interpreted together with planetary condition and aspects.",
        "keywords": ["sixth house", "eighth house", "medical", "health symbolism"],
    },
    {
        "id": "daath.planetary.powers",
        "source": "daath_medical",
        "system": "MEDICAL_ASTROLOGY",
        "topics": ["medical_astrology", "planets", "symbolism"],
        "locator": "Planetary Powers and Principles / Biodynamic Action",
        "summary": "Planets are assigned historical physiological and functional symbolism; these correspondences describe symbolic tendencies, not clinical diagnosis.",
        "keywords": ["Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "physiology", "symbolism"],
    },
    {
        "id": "daath.guardrail",
        "source": "daath_medical",
        "system": "MEDICAL_ASTROLOGY",
        "topics": ["medical_astrology", "safety"],
        "locator": "Application policy for this software",
        "summary": "Medical-astrology material is historical and symbolic only. It must never be converted into a diagnosis, prognosis, treatment recommendation, or statement of medical risk.",
        "keywords": ["safety", "medical advice", "diagnosis", "prognosis", "treatment"],
    },
    {
        "id": "merton.heliocentric.separation",
        "source": "merton_heliocentric",
        "system": "HELIOCENTRIC_HISTORICAL",
        "topics": ["heliocentric", "method", "system_separation"],
        "locator": "Argument and Intention / Earlier Geocentric System",
        "summary": "The source presents heliocentric astrology as a distinct system with its own astronomical and interpretive premises; it should not be silently merged with geocentric or Vedic rules.",
        "keywords": ["heliocentric", "geocentric", "system", "astronomy", "method"],
    },
    {
        "id": "merton.astronomy.foundation",
        "source": "merton_heliocentric",
        "system": "HELIOCENTRIC_HISTORICAL",
        "topics": ["astronomy", "coordinates", "zodiac"],
        "locator": "Astronomy / Celestial Sphere / Latitude and Longitude",
        "summary": "The book treats astronomical geometry, coordinate systems and planetary paths as the technical basis on which its interpretive system is built.",
        "keywords": ["astronomy", "celestial sphere", "latitude", "longitude", "right ascension", "ecliptic"],
    },
]

TOPIC_ALIASES = {
    "planet": "planets",
    "planetary": "planets",
    "natal chart": "natal",
    "genethliacal": "genethliacal",
    "radix": "natal",
    "career": "employment",
    "work": "employment",
    "profession": "employment",
    "finance": "money",
    "wealth": "money",
    "relationship": "marriage",
    "love": "marriage",
    "progression": "progressions",
    "return": "solar_returns",
    "medical": "medical_astrology",
    "health": "medical_astrology",
}
